### ISSUE TITLE
Is the output of Meter affected by mastering of the track?

### ISSUE THREAD

**Issue by rexendevar** [airwindows/Meter#13]
I know this title isn't very good at all, but I didn't know how to explain it. My music library is all in mp3 format - every album I download, I normalize in Reaper so there is a maximum true peak of -1dB across the entire album. This means that tracks which previously would have clipped extensively no longer do, but it also means of course that the overall loudness across each track and the value of each peak is turned down. My question is, does Meter do anything to compensate for this, or are all my test measurements going to be affected by it? Will it affect the measured energy level?

**Comment by airwindows** [comment]
All that will happen is your examples won't show 'red lines for clipping'. On the whole it won't change that much, because Meter's dots and lines are measured by peak and slew energy, not 'maximum loudness', and even the 'hit record line' is not keying off maximum loudness, but off density of the blue dots.

So it might have a very minor effect but won't significantly change anything. The only part that will be different is, it will never show clipping the way the native meter will show it, because you've prevented that ever happening :)

**Comment by rexendevar** [comment]
thank you! i missed the whole thing about slew energy... i didn't watch much of the explainer video lol :)
